### ISSUE TITLE
Error in development from guard-compat?

### ISSUE THREAD

**Issue by conzett** [guard/guard-rspec#312]
Upgrading to guard-rspec 4.5 and running `bundle exec gaurd` in development gives me:

```shell
/gems/guard-compat-1.2.1/lib/guard/compat/plugin.rb:17:in `initialize':
either Guard has not been required or you did not include
guard/compat/test/helper (NotImplementedError)
```
My gemfile has:

```ruby
group :development do                                
  gem 'guard-brakeman', require: false
  gem 'guard-jasmine', require: false           
  gem 'guard-rspec', require: false             
  gem 'guard-rubocop', require: false
end                                             
```
I have not changed anything else other than updating guard-rspec, I am running it with spring but I have stopped and restarted the spring instance. Any upgrade instructions that I missed?

**Comment by e2** [comment]
It's possible I broke something. It looks weird to me.

Probably an edge case. 

Ideally at *least* 'guard/plugin' should be included somewhere (normally in Guard), so this is strange.

Could you create a repo that reproduces this? (it seems to work for me - could be an issue with a specific set of gems). Thanks!

**Comment by conzett** [comment]
@e2 This is the simplest way to reproduce it, just tried on a fresh repository:

1. Generate a new Rails 4.2 application
2. Use this Gemfile
  ```ruby
    source 'https://rubygems.org' 
                                   
    gem 'rails', '4.2.0'               
    gem 'sqlite3'                      
    gem 'sass-rails', '~> 5.0'         
    gem 'uglifier', '>= 1.3.0'         
    gem 'coffee-rails', '~> 4.1.0'     
    gem 'jquery-rails'                 
                                   
    group :development do              
      gem 'guard-rspec', require: false
    end
```
3. `install && bundle exec guard init`

Produces the following error:

```shell

/Users/gconzett/.gem/ruby/2.0.0/gems/guard-2.2.5/lib/guard/plugin_util.rb:129:in `block in add_to_guardfile': undefined method `template' for Guard::Compat:Module (NoMeth
odError)
        from /Users/gconzett/.gem/ruby/2.0.0/gems/guard-2.2.5/lib/guard/plugin_util.rb:126:in `open'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/guard-2.2.5/lib/guard/plugin_util.rb:126:in `add_to_guardfile'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/guard-2.2.5/lib/guard/guardfile/generator.rb:57:in `initialize_template'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/guard-2.2.5/lib/guard/guardfile/generator.rb:83:in `block in initialize_all_templates'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/guard-2.2.5/lib/guard/guardfile/generator.rb:83:in `each'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/guard-2.2.5/lib/guard/guardfile/generator.rb:83:in `initialize_all_templates'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/guard-2.2.5/lib/guard/guardfile.rb:39:in `initialize_all_templates'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/guard-2.2.5/lib/guard/cli.rb:162:in `init'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/gconzett/.gem/ruby/2.0.0/gems/guard-2.2.5/bin/guard:6:in `<top (required)>'
        from /Users/gconzett/.gem/ruby/2.0.0/bin/guard:23:in `load'
        from /Users/gconzett/.gem/ruby/2.0.0/bin/guard:23:in `<main>'
```
I am using MRI ruby-2.0.0-p576

**Comment by e2** [comment]
@conzett - you should add 'guard' to the Gemfile - at least 2.10.5. (your version is "ancient" at this point).

Sorry about this - Guard is no longer included in the dependencies (for really obscure reasons).

**Comment by conzett** [comment]
Ah ok I was going off of the gemspec which lists the guard dependency at `~> 2.1`. What is the minimum supported version of guard? Thanks for your help!

**Comment by e2** [comment]
@conzett - since Guard is for development, it's best to always have the latest version of it and it's plugins. In fact, if something is wrong in the latest version - just file an issue (I usually fix bugs fast).

**Comment by Fryie** [comment]
I could also fix this issue by updating guard and guard-rails. It turns out, I had a very ancient version of compass which locked guard to an old release.
