### ISSUE TITLE
Exception: NoMethodError: undefined method `match' for nil:NilClass

### ISSUE THREAD

**Issue by perlun** [guard/guard-rspec#318]
With this `Guardfile`, I get this exception (after it runs the specs successfully one time):

```
guard :rspec, spec_paths: ['*spec'], cmd: 'rspec -I. -Iapi/_lib -Iapi_spec --tty --color --format d', all_on_start: true do
  watch(%r{^.*spec/.+}) { '*spec' }
  watch(%r{^api/(.+)\.rb}) { 'api_spec' }
  watch(%r{^workers/.+}) { 'workers_spec' }
  watch('api_spec/spec_helper.rb') { '*spec' }

  watch(%r{^spec_data/(.+)}) { '*spec' }
end
```

Here is the error:

```
Guard::RSpec failed to achieve its <start>, exception was:
> [#21AE104ECFD8] NoMethodError: undefined method `match' for nil:NilClass
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec/notifier.rb:32:in `_parse_summary'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec/notifier.rb:12:in `notify'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec/runner.rb:106:in `_process_run_result'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec/runner.rb:45:in `block in _run'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec/runner.rb:44:in `tap'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec/runner.rb:44:in `_run'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec/runner.rb:24:in `run_all'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec.rb:33:in `block in run_all'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec.rb:48:in `_throw_if_failed'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec.rb:33:in `run_all'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec.rb:29:in `start'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:82:in `block in _supervise'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:79:in `catch'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:79:in `_supervise'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:22:in `block (3 levels) in run'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:119:in `block (2 levels) in _run_group_plugins'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:117:in `each'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:117:in `block in _run_group_plugins'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:116:in `catch'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:116:in `_run_group_plugins'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:21:in `block (2 levels) in run'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:20:in `each'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:20:in `block in run'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack.rb:32:in `unit_of_work'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/runner.rb:18:in `run'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/commander.rb:34:in `start'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/cli.rb:113:in `start'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:32:in `execute'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#21AE104ECFD8] /Users/plundberg/git/indirect-purchasing-backoffice-app/vendor/bundle/ruby/2.2.0/gems/guard-2.12.5/bin/_guard-core:11:in `<main>'
```

**Comment by e2** [comment]
Can you create a small repo to reproduce this? 

(Basically, RSpec is creating some unexpected output - and if I don't know what it is, I can't fix it.)

Or If you prefer, you can edit the `lib/guard/rspec/runner.rb` file and in the `_command_output` method, add the following line:

```ruby
      def _command_output
        formatter_tmp_file = _tmp_file(options[:chdir])
        lines = File.readlines(formatter_tmp_file)
        STDERR.puts "OUTPUT FROM RSPEC: #{lines.inspect}"
        summary = lines.first.strip
        failed_paths = lines[1..11].map(&:strip).compact
```

And paste the output here or in a gist - and I should have enough fix this quickly.

Thanks.

**Comment by perlun** [comment]
Thank you. Extremely odd - I can't seem to reproduce this any more. :cry: Both red and green tests work as expected. Have to close for now, will reopen if I can reproduce it again.
