### ISSUE TITLE
bundle exec guard fails

### ISSUE THREAD

**Issue by brentgreeff** [guard/guard-rspec#426]
Issue seems to be referenced here: https://www.gitmemory.com/issue/guard/guard/966/708039727

I am using Rails 4.2 - so next bet is to try older versions of guard, but I was hoping this would look familiar to someone:

```
22:14:04 - INFO - Bye bye...
/gems/gems/guard-2.17.0/lib/guard/jobs/pry_wrapper.rb:294:in `initialize': wrong number of arguments (given 3, expected 0) (ArgumentError)
	from /gems/gems/guard-2.17.0/lib/guard/jobs/pry_wrapper.rb:294:in `new'
	from /gems/gems/guard-2.17.0/lib/guard/jobs/pry_wrapper.rb:294:in `_configure_prompt'
	from /gems/gems/guard-2.17.0/lib/guard/jobs/pry_wrapper.rb:161:in `_setup'
	from /gems/gems/guard-2.17.0/lib/guard/jobs/pry_wrapper.rb:78:in `initialize'
	from /gems/gems/guard-2.17.0/lib/guard/interactor.rb:17:in `new'
	from /gems/gems/guard-2.17.0/lib/guard/interactor.rb:17:in `initialize'
	from /gems/gems/guard-2.17.0/lib/guard.rb:67:in `new'
	from /gems/gems/guard-2.17.0/lib/guard.rb:67:in `setup'
	from /gems/gems/guard-2.17.0/lib/guard/commander.rb:32:in `start'
	from /gems/gems/guard-2.17.0/lib/guard/cli/environments/valid.rb:16:in `start_guard'
	from /gems/gems/guard-2.17.0/lib/guard/cli.rb:122:in `start'
	from /gems/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /gems/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /gems/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /gems/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /gems/gems/guard-2.17.0/lib/guard/aruba_adapter.rb:32:in `execute'
	from /gems/gems/guard-2.17.0/lib/guard/aruba_adapter.rb:19:in `execute!'
	from /gems/gems/guard-2.17.0/bin/_guard-core:11:in `<main>'
```

**Comment by ngudbhav** [comment]
Facing this on rails 5 as well

**Comment by alagos** [comment]
Probably a late reply, but I'm with a rails 4.2/ruby 2.4 project, using guard-rspec (4.7.3) and guard (2.18.1) with no problems.
